name: Matrix Strategy

on:
  push:
    branches: [ "feat/auth" ]

jobs:
  test-node-versions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Yahan tu list banata hai
        node-version: [14, 16, 18]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          # Yahan hum hardcode '18' nahi likhenge, matrix se uthayenge
          node-version: ${{ matrix.node-version }}

      - name: Run Tests
        run: |
          echo "Testing on Node version: $(node -v)"
          npm install
          npm test