apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-sa
