apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-ns-quota
  namespace: default
spec:
  hard:
    # --- CPU Resources ---
    requests.cpu: "4"
    limits.cpu: "8"

    # --- Memory Resources ---
    requests.memory: "4Gi"
    limits.memory: "8Gi"

    # --- Object Counts ---
    pods: "10"
    persistentvolumeclaims: "4"
    services: "10"
