apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-ns-quota
  namespace: default
spec:
  hard:
    
    requests.cpu: "8"
    limits.cpu: "16"

    
    requests.memory: "128Gi" 
    limits.memory: "32Gi"

    pods: "20"
    persistentvolumeclaims: "10"
    services: "15"