apiVersion: v1
kind: Service
metadata:
  name: identity-svc
spec:
  type: LoadBalancer
  selector:
    app: identity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment        # Kind badal kar Deployment kar diya
metadata:
  name: identity-deploy # Deployment ka naya naam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  strategy:             # Rolling update strategy (Default yahi hoti hai)
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: identity
    spec:
      serviceAccountName: identity-sa
      initContainers:
      - name: wait-for-mongo
        image: busybox:1.28
        envFrom:
          - configMapRef:
              name: identity-cm
        command: ['sh', '-c', "until nc -zv $MONGO_HOST $MONGO_PORT; do echo 'Waiting...'; sleep 2; done"]
      containers:
      - name: identity-container
        image: raunakraj010/identity-service:final
        resources:           # <--- YE ADD KARO
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: my-config-map
          mountPath: "/etc/config"
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: identity-cm
        # Probes wahi rahenge jo tumne set kiye hain
        startupProbe:
          httpGet:
            path: /
            port: 8001
          failureThreshold: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
      volumes:
      - name: my-config-map
        configMap:
          name: identity-cm
