apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- identity.yml
- kafka.yml
- zookepper.yml
- redis.yml
- post.yml
- configMap.yml
- mongodb-sts.yml
- app-service-account.yml
- storage-class.yml
- final-cluster-quota.yml
- postConfigMap.yml
- post-app-hpa.yml

images:
- name: raunakraj010/identity-service
  newName: us-central1-docker.pkg.dev/project-5e783ec5-d363-4cc7-884/social-app-repo/identity-service
  newTag: a08cd0cbc5683a913eeea719c5cea1d497977239
- name: raunakraj010/post-service
  newName: us-central1-docker.pkg.dev/project-5e783ec5-d363-4cc7-884/social-app-repo/post-service
  newTag: a08cd0cbc5683a913eeea719c5cea1d497977239
