apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: post-service
    spec:
      serviceAccountName: post-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: # "Must have" rule
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      initContainers:
      # 1. Wait for MongoDB
      - name: wait-for-mongo
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv mongodb-svc 27017; do echo 'Waiting for Mongo...'; sleep 2; done"]

      # 2. Wait for Redis
      - name: wait-for-redis
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv redis-svc 6379; do echo 'Waiting for Redis...'; sleep 2; done"]

      # 3. Wait for Kafka
      - name: wait-for-kafka
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv kafka-svc 9092; do echo 'Waiting for Kafka...'; sleep 2; done"]

      containers:
      - name: post-container
        image: raunakraj010/post-service:v4
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: post-cm
        volumeMounts:
        - name: post-config-vol
          mountPath: "/etc/config"

        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        startupProbe:
          httpGet:
            path: /health
            port: 8002
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10

      volumes:
      - name: post-config-vol
        configMap:
          name: post-cm
---
apiVersion: v1
kind: Service
metadata:
  name: post-svc
spec:
  type: ClusterIP
  selector:
    app: post-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
